language: java
jdk:
- oraclejdk8
sudo: false # faster builds

before_install:
  - chmod +x mvnw
  - pip install --user codecov

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
